sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

env:
  - CASSANDRA_CLUSTER_HOSTS=localhost APP_PORT=2551
  - secure: jUoroyWWu1OU5SSrosqPRAemQKvt2LoqwgdCw9hEzLfBjckW55rOTSRltJ02BBxVPT1A7gdZOhCV15ehj6ESl9WPGvNMXq3yqOIuotM9Xx9Z/SHvJWvA+GERnryBCTwyI7DCYev4GhEFEBTHvbxenssCKPotM33g031TrwIRhE7mo3zQGd72ACWeEp0fbke5ndYwz45rBdqMi1uo+dyjMe1mia7O67SwtFa++LrKR7bBoWgsTcY7FfaBmTX9j/ZpmZO4b4W+6ot28ZjwIHejtY3xVDJMXAQWv3vdoQ61bBbRBy2vGIJOiXr0ePDLIBVtGX2Im3ii5biiTsCZwlGv1teRVWa/p8nV7D+4lKX0TzLqSfArCoCyRuGs3FzHfTLkZmhSexdjJ57w4hxp5uf0BeZA2Dp5IaPXvmwjgebgPn+Tzh2nKi4M8ViXSbV5pEClmLGNs+xj2hLAe7eYDTlXrqpV8C7UQ8JN3KSCLLqYiv0bqINKRWN6mf0mr0SeaBQFJ0ZHLWsSBnChYaeGjSCXZcakUenEbEcZxJCAco96Au1quJhv28yq7imCuyHcxRFhL8YNrhsDi5ujBZGwM0v1c9EffxFZYfO6Id6D9V3TJvO2UE8w7/7VBhFU6Lkr/lYPN9QgDStPIyrvOq85j0jTZIShOO9EvGHN1KHvCjVpgHQ=
language: scala

scala: 2.12.10

install:
  - nvm install node
  - npm install newman

jdk:
- openjdk14

script:
  - echo INTERNALURL
  - env
  - if [[ 'grep -iRl "${INTERNALURL}" ./' ]]; then exit 1; fi
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

  - ./run_travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
