sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

env:
  - CASSANDRA_CLUSTER_HOSTS=localhost APP_PORT=2551
  - secure: C97CnHdxfXwGe1wA5Y2VEW0JfVE2HZMAhPhvsKR9LM0kRu/EbTwp4PyHQM30zDAFT8apFTYnVuzzpdCCIQ5GUKt/TAi+1Ip06bcV5xVSSaaxRB0NqiRQi/nE418GoHP/wES0Q7DgA47YGPruaGKwonVo1OTXpsVgBbbVA25N7fQvmEzRdfyzt8nkj/0M4tNx+X9tmmqRhYe5TBzaKg5XhV1AE76+agYZj8ByUKa0YstHqd9XaZ1gr6Q7EYUILr1uoQSgPcfwIn/MGNElNV2a0lJiz/rIWtMCuyfiWtQbutm3izVRlYYNqzLwZiw/p8TLKCUdHqNrdKyFuYipFLyZ28huYraVoDnAcdDM5JPnkGn6mUYB2uNQZztb4AUN0os0zcOiqmSly0IUwPu0K6WWzjXWoK5LZFfN3CrghzLa7anypUwamUvDVbuhtwD34/oaTajEEqC1W1+R7q816rN5NRueGfrSBLqbboteQP+s15j0ponaRJGk2octbXSgc0htH36XBRo0RCy7EC5u0+L1TpKqOg3ypgeLy+oUbkhjXitvHobFCBU2MBKP/T4/DSm5Sen/2LcPxWbcLSfDsb/lbSX2nGhlAvKWMiCw/BwiOUBbTlGPufnx1n2IcWFGlq55A+uZcT8STpXe1Y+c4sZgff5uklQnoJE2ueOe2Z+nOos=

language: scala

scala: 2.12.10

install:
  - nvm install node
  - npm install newman

jdk:
- openjdk14

script:
  - if [[ 'grep -iRl "${INTERNALURL}" ./' ]]; exit 1; fi
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

  - ./run_travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
